language: node_js
node_js:
    - "lts/*"
install:
  - yarn
  - yarn global add codecov
cache:
  yarn: true
  directories:
  - node_modules

script:
  - yarn test
  - yarn build

#deploy:
#  provider: npm
#  email: "oliver@devbutze.com"
#  api_key: "YOUR_AUTH_TOKEN"
#  on:
#    tags: true
#    branch: master

after-success:
  - bash <(curl -s https://codecov.io/bash)
