language: node_js
node_js:
- lts/*
install:
- yarn
- yarn global add codecov
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn test
- yarn build
after-success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: npm
  email: oliver@devbutze.com
  api_key:
    secure: V4RYqlOdO4iFjznd3AJUZEnq2ZPc1vjS2/hbAyW9+jnSlOoBul7kA3+PvFl8o9ECQ07CeI9MDCnQmep7oNUk0k0S9DmBIgTt2nb5uJ8s5Sm05ro81wiYoNEEjD1XgOG3YmaY0m5g3TXYK29YRXG83ZXmqRE1ZnZUz5B5o7bUaHVd0gMmoFyUdXjkrotsKImq8ZgI3bJbigSKZQWekpsuwfOg3sQU6jXjf3zojRzY7sZqOfkZmCbCZ59AXiDwH9rxu/4xZeNLqpzdZaBRTsGu331vwd5ao2ZJpeRwu/bOPju/8J4i/vp8T0EuebYoJfu1pYTco94Yw+PhRy56nMCczxoNGrWfdpxDAEcyHpM8eh+AZliVifE+38JFgiYsDc8f9+wcbClRTUbnACbk9v2ztjcn11gDC0VIABIYKdAH1KGM2VOtXFXTCHzELgsGYT8ABm7aDYJkGp0WhcDekfIVjpA1mQVmaQYVvhNJ7e7SJPk8QF9xuFhCcd19Zwv19jbXqEAJKdrfwrl3RNiSB2Uc9fiqbpG8Gf53VEpu5xROTz/99L8Ts16HpERW77ANn0INrNrttsQZ5G8kI7HOnB0xtjZ1j8GpxdRFUA4NZLn+U2SMPKJ2t5/A9g4V/jDviKV6yqo/ZblAA6cHXiqk/6v/RXwkD53jtQPxjAkQjEzcRos=
  skip_cleanup: true
  on:
    tags: true
    repo: ohager/burst-autoplotter
    all_branches: true
