language: node_js
node_js:
- lts/*
install:
- yarn
- yarn global add codecov
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn test
- yarn build
after-success:
- bash <(curl -s https://codecov.io/bash)
